### ISSUE TITLE
Feature request: uploading images during private conversation

### ISSUE THREAD

**Issue by dh256git** [Grapheel/IRIS#7]
I'd like to request the following IRIS superpower(s), change(s):

 - [ ] Uploading images when sending message to volunteer:
  * I uploaded an image I created, asking people to check. I've got a great response, but there were mistakes I needed to correct. Now I have the modified image, but it would make sense to send it to the same volunteer to ask if I managed to fix the issue, rather than start from scratch with new volunteers. So an option to upload an image when in the conversation view, sending replies.

**Comment by tingard** [comment]
Interesting idea... My main concern with adding this feature is that it could lead to students going back to volunteers that they know to send new images, rather than putting it out into the pool. It also could lead to Grapheel hosting a large number of images.
Perhaps asking the volunteer for an email address to send the corrected image to is better for this use-case, though this is something we'll need to discuss further as a team.
